#!/bin/bash

python affordable_housing.py &
python cost_of_living.py &
python Foreign_Buyer.py &
python foreign_buyer_ban.py &
python foreign_home_buyer.py &
python foreign_investors.py &
python Freedom_Convoy.py &
python Generational_Wealth.py &
python home_owner.py &
python housing_crisis.py &
python housing_market.py &
python Increase_of_prices.py &
python increase_price_home.py &
python increase_price_housing.py &
python increase_prices_home.py &
python increase_prices_housing.py &
python inflation.py &
python interest_rate_home.py &
python interest_rate_housing.py &
python low_income_housing.py &
python minimum_wage.py &
python property_tax_canada.py &
python rental_market.py &
python rising_price_home.py &
python rising_price_housing.py &
python Rising_prices.py &
python rising_prices_home.py &
python rising_prices_housing.py &
python social_assistance.py &
python standard_of_living.py &